=== elevate/sharpresume/HRXML200704/HR-XML-2_5/StandAlone/StaffingShift.xsd
<?xml version="1.0"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Chuck Allen (HR-XML Consortium, Inc.) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:oa="http://www.openapplications.org/oagis" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" targetNamespace="http://ns.hr-xml.org/2007-04-15" elementFormDefault="qualified" version="2007-04-15">
	<xsd:annotation>
		<xsd:documentation>"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"

Terms of license can be found in license.txt.
</xsd:documentation>
		<xsd:documentation>Stand alone (but non-normative) version of schema, with all "includes" inserted explicitly.  This file is auto-generated.  It should be considered a "convenience" alternative to the normative versions.</xsd:documentation>
		<xsd:documentation>After merging all includes, the result is passed through a stylesheet which deletes any duplicative global components as well as any unused global types.  Finally, it sorts by component name.  Be sure to check the Xml Namespaces to ensure this result is what you requested.</xsd:documentation>
	</xsd:annotation>
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xsd:element name="StaffingShift" type="StaffingShiftType"/>
	<xsd:simpleType name="AnyDateTimeNkNaType">
		<xsd:union memberTypes="LocalDateType DateType LocalDateTimeType DateTimeType NotKnownLiteral NotApplicableLiteral"/>
	</xsd:simpleType>
	<xsd:simpleType name="DateTimeType">
		<xsd:restriction base="xsd:dateTime">
			<xsd:pattern value="\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d(Z|(\+|-)\d\d:\d\d)"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DateType">
		<xsd:restriction base="xsd:date">
			<xsd:pattern value="\d\d\d\d-\d\d-\d\d(Z|(\+|-)\d\d:\d\d)"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LocalDateTimeType">
		<xsd:restriction base="xsd:dateTime">
			<xsd:pattern value="\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LocalDateType">
		<xsd:restriction base="xsd:date">
			<xsd:pattern value="\d\d\d\d-\d\d-\d\d"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LocalTimeNkNaType">
		<xsd:union memberTypes="LocalTimeType NotKnownLiteral NotApplicableLiteral"/>
	</xsd:simpleType>
	<xsd:simpleType name="LocalTimeType">
		<xsd:restriction base="xsd:time">
			<xsd:pattern value="\d\d:\d\d:\d\d"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NotApplicableLiteral">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="notApplicable"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NotKnownLiteral">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="notKnown"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TimeType">
		<xsd:restriction base="xsd:time">
			<xsd:pattern value="\d\d:\d\d:\d\d(Z|(\+|-)\d\d:\d\d)"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="EntityIdType">
		<xsd:sequence>
			<xsd:element name="IdValue" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="name" type="xsd:string" use="optional"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="validFrom" type="AnyDateTimeNkNaType" use="optional"/>
		<xsd:attribute name="validTo" type="AnyDateTimeNkNaType" use="optional"/>
		<xsd:attribute name="idOwner" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="StaffingShiftType">
		<xsd:sequence>
			<xsd:element name="Id" type="EntityIdType"/>
			<xsd:element name="Name" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Hours" type="xsd:decimal" minOccurs="0"/>
			<xsd:element name="StartTime" type="LocalTimeNkNaType" minOccurs="0"/>
			<xsd:element name="EndTime" type="LocalTimeNkNaType" minOccurs="0"/>
			<xsd:element name="TypeHours" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Comment" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ExternalStaffingShiftSetId" type="EntityIdType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="shiftPeriod">
			<xsd:annotation>
				<xsd:documentation> Numeric values conform to: ISO 8601 2nd Edition; ISO8601:2000(E); pub 2000-12-15, Data elements and interchange formats,  Information interchange,  Representation of dates and times,  http://www.iso.ch/cate/d26780.html/ 

				</xsd:documentation>
				<xsd:documentation>1 = Monday, 2 = Tuesday, 3 = Wednesday, 4 = Thursday, 5 = Friday, 6 = Saturday, 7 = Sunday</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="monthly"/>
					<xsd:enumeration value="weekly"/>
					<xsd:enumeration value="daily"/>
					<xsd:enumeration value="1"/>
					<xsd:enumeration value="2"/>
					<xsd:enumeration value="3"/>
					<xsd:enumeration value="4"/>
					<xsd:enumeration value="5"/>
					<xsd:enumeration value="6"/>
					<xsd:enumeration value="7"/>
					<xsd:enumeration value="event"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute ref="xml:lang"/>
	</xsd:complexType>
</xsd:schema>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/SIDES/StaffingShift.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Chuck Allen (HR-XML Consortium, Inc.) -->
<StaffingShift xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 StaffingShift.xsd" shiftPeriod="monthly">
	<Id validFrom="2004-01-01" validTo="2004-12-31">
		<IdValue>Regular</IdValue>
	</Id>
	<Name> First</Name>
	<Hours>37</Hours>
	<StartTime>07:00:00</StartTime>
	<EndTime>14:00:00</EndTime>
	<TypeHours> Regular</TypeHours>
	<Comment>String</Comment>
	<ExternalStaffingShiftSetId>
		<IdValue>37291</IdValue>
	</ExternalStaffingShiftSetId>
</StaffingShift>
