=== elevate/sharpresume/HRXML200704/HR-XML-2_5/TimeCard/TimeCard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ns.hr-xml.org/2007-04-15" xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="2007-04-15">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../../W3C/xml.xsd"/>
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: TimeCard.xsd
Status: Recommendation
Date this version: 2007-04-15
Purpose: Defines XSD for Time Capture
Author(s): Bill Kerr - Oracle Corporation, Paul Kiel - HR-XML, Gail Bubsey - Kelly Services, Erwin Folmer - TNO, Time Workgroup
Documentation: TimeExpenseReporting.html
Terms of license can be found in license.txt.
		
		</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="../CPO/EntityIdType.xsd"/>
	<xsd:include schemaLocation="../CPO/PersonName.xsd"/>
	<xsd:include schemaLocation="../CPO/UserArea.xsd"/>
	<xsd:include schemaLocation="../CPO/ISOUtilities.xsd"/>
	<xsd:element name="TimeCard" type="TimeCardType"/>
	<xsd:simpleType name="ActionCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Add"/>
			<xsd:enumeration value="Change"/>
			<xsd:enumeration value="Void"/>
			<xsd:enumeration value="Unchanged"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DayAssignmentType">
		<xsd:union memberTypes="DayAssignmentEnumerationType LocalDateType xsd:nonNegativeInteger"/>
	</xsd:simpleType>
	<xsd:simpleType name="DayAssignmentEnumerationType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="previous"/>
			<xsd:enumeration value="current"/>
			<xsd:enumeration value="next"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="AdditionalDataType" mixed="true">
		<xsd:annotation>
			<xsd:documentation>In order to prevent a possible "ambiguous content model" errors in an instance, unbounded sequences were either eliminated from or deprecated in all HR-XML schemas. Removing unbounded sequences ensures that ambiguous errors are not found in an instance.  The unbounded sequence here is officially deprecated and will be changed to a single sequence.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:any namespace="##any" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="ApprovalInfoType">
		<xsd:sequence>
			<xsd:element name="Person" type="TimeCardPersonType"/>
			<xsd:element name="ApprovedDateTime" type="AnyDateTimeType"/>
			<xsd:element name="Comment" type="CommentType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="approverType" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="CommentType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute ref="xml:lang"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="SubmitterInfoType">
		<xsd:sequence>
			<xsd:element name="Person" type="TimeCardPersonType" minOccurs="0"/>
			<xsd:element name="Source" type="xsd:string" minOccurs="0"/>
			<xsd:element name="SubmittedDateTime" type="AnyDateTimeType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TimeCardPersonType">
		<xsd:sequence>
			<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
			<xsd:element ref="PersonName" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TimeCardType">
		<xsd:sequence>
			<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
			<xsd:element name="ReportedResource">
				<xsd:complexType>
					<xsd:choice>
						<xsd:element name="Person" type="TimeCardPersonType"/>
						<xsd:element name="Resource">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="Id" type="EntityIdType" minOccurs="0" maxOccurs="unbounded"/>
									<xsd:element name="ResourceName" type="xsd:string" minOccurs="0"/>
									<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
								</xsd:sequence>
								<xsd:attribute name="type" type="xsd:string"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ReportedTime" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="PeriodStartDate" type="AnyDateTimeType"/>
						<xsd:element name="PeriodEndDate" type="AnyDateTimeType"/>
						<xsd:element name="ReportedPersonAssignment" minOccurs="0">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:choice maxOccurs="unbounded">
							<xsd:element name="TimeInterval">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
										<xsd:element name="StartDateTime" type="AnyDateTimeType"/>
										<xsd:choice>
											<xsd:sequence>
												<xsd:element name="EndDateTime" type="AnyDateTimeType"/>
												<xsd:element name="Duration" type="TimeCardDuration" minOccurs="0"/>
											</xsd:sequence>
											<xsd:element name="Duration" type="TimeCardDuration"/>
										</xsd:choice>
										<xsd:element name="PieceWork" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Piece">
														<xsd:complexType>
															<xsd:sequence>
																<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
																<xsd:element name="PieceValue" type="xsd:string"/>
															</xsd:sequence>
														</xsd:complexType>
													</xsd:element>
													<xsd:element name="Quantity">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:double">
																	<xsd:attribute name="unitOfMeasure" type="xsd:string"/>
																</xsd:extension>
															</xsd:simpleContent>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="RateOrAmount" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:double">
														<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
														<xsd:attribute name="type" type="xsd:string" use="required"/>
														<xsd:attribute name="period" type="xsd:string"/>
														<xsd:attribute name="multiplier" type="xsd:double"/>
														<xsd:attribute name="toBeBilled" type="xsd:boolean"/>
														<xsd:attribute name="toBePaid" type="xsd:boolean"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Allowance" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
													<xsd:element name="StartDate" type="AnyDateTimeType" minOccurs="0"/>
													<xsd:element name="EndDate" type="AnyDateTimeType" minOccurs="0"/>
													<xsd:element name="Amount" minOccurs="0">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:double">
																	<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
																</xsd:extension>
															</xsd:simpleContent>
														</xsd:complexType>
													</xsd:element>
													<xsd:element name="Quantity" type="xsd:double" minOccurs="0"/>
													<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
													<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
													<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
													<xsd:element name="Comment" type="CommentType" minOccurs="0" maxOccurs="unbounded"/>
												</xsd:sequence>
												<xsd:attribute name="type" type="xsd:string" use="required"/>
												<xsd:attribute name="billable" type="xsd:boolean"/>
												<xsd:attribute name="actionCode" type="ActionCodeType"/>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
										<xsd:element name="Comment" type="CommentType" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
									<xsd:attribute name="type" type="xsd:string" use="required"/>
									<xsd:attribute name="dayAssignment" type="DayAssignmentType"/>
									<xsd:attribute name="billable" type="xsd:boolean"/>
									<xsd:attribute name="actionCode" type="ActionCodeType"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="TimeEvent">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
										<xsd:element name="EventDateTime" type="AnyDateTimeType"/>
										<xsd:element name="RateOrAmount" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:double">
														<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
														<xsd:attribute name="type" type="xsd:string" use="required"/>
														<xsd:attribute name="period" type="xsd:string"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
										<xsd:element name="Comment" type="CommentType" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
									<xsd:attribute name="type" type="xsd:string" use="required"/>
									<xsd:attribute name="dayAssignment" type="DayAssignmentType"/>
									<xsd:attribute name="billable" type="xsd:boolean"/>
									<xsd:attribute name="actionCode" type="ActionCodeType"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Expense">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
										<xsd:element name="ExpenseDate" type="AnyDateTimeType"/>
										<xsd:element name="ExpenseAmount">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:double">
														<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
										<xsd:element name="Comment" type="CommentType" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
									<xsd:attribute name="type" type="xsd:string" use="required"/>
									<xsd:attribute name="billable" type="xsd:boolean"/>
									<xsd:attribute name="actionCode" type="ActionCodeType"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Allowance">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Id" type="EntityIdType" minOccurs="0"/>
										<xsd:element name="StartDate" type="AnyDateTimeType" minOccurs="0"/>
										<xsd:element name="EndDate" type="AnyDateTimeType" minOccurs="0"/>
										<xsd:element name="Amount" minOccurs="0">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:double">
														<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Quantity" type="xsd:double" minOccurs="0"/>
										<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
										<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
										<xsd:element name="Comment" type="CommentType" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
									<xsd:attribute name="type" type="xsd:string" use="required"/>
									<xsd:attribute name="billable" type="xsd:boolean"/>
									<xsd:attribute name="actionCode" type="ActionCodeType"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
						<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="status" type="xsd:string">
						<xsd:annotation>
							<xsd:documentation>The preferred statuses are: Raw, Processed, Submitted, Rejected, Approved, Final. Please look at the documentation for definitions.</xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="SubmitterInfo" type="SubmitterInfoType" minOccurs="0"/>
			<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="AdditionalData" type="AdditionalDataType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="UserArea" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute ref="xml:lang"/>
	</xsd:complexType>
	<xsd:simpleType name="TimeCardDuration">
		<xsd:union memberTypes="xsd:duration xsd:decimal"/>
	</xsd:simpleType>
</xsd:schema>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/TimeCard/TimeCard7.xml
<?xml version="1.0" encoding="UTF-8"?>
<TimeCard xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
TimeCard.xsd">
	<ReportedResource>
		<Person>
			<Id>
				<IdValue>d026194</IdValue>
			</Id>
		</Person>
	</ReportedResource>
	<ReportedTime status="Approved">
		<PeriodStartDate>2006-05-01</PeriodStartDate>
		<PeriodEndDate>2006-05-18</PeriodEndDate>
		<TimeInterval type="Regular" billable="true">
			<StartDateTime>2006-05-07</StartDateTime>
			<EndDateTime>2006-05-07</EndDateTime>
			<Duration>PT8H</Duration>
			<Allowance type="Riskallowance" billable="true">
				<StartDate>2006-05-06</StartDate>
				<ApprovalInfo>
					<Person>
						<PersonName>
							<FormattedName>Elvira Annevelink</FormattedName>
						</PersonName>
					</Person>
					<ApprovedDateTime>2006-05-09</ApprovedDateTime>
				</ApprovalInfo>
			</Allowance>
			<SubmitterInfo>
				<Person>
					<PersonName>
						<FormattedName>Erwin Folmer</FormattedName>
					</PersonName>
				</Person>
				<SubmittedDateTime>2006-05-08</SubmittedDateTime>
			</SubmitterInfo>
			<Comment>Aaabbbccc</Comment>
		</TimeInterval>
		<Expense type="Meal" billable="true">
			<ExpenseDate>2006-05-07</ExpenseDate>
			<ExpenseAmount currency="USD">10</ExpenseAmount>
		</Expense>
		<TimeInterval type="Vacation" actionCode="Add">
			<StartDateTime>2006-05-08</StartDateTime>
			<EndDateTime>2006-05-11</EndDateTime>
		</TimeInterval>
		<TimeInterval type="Regular" actionCode="Change">
			<StartDateTime>2006-05-14</StartDateTime>
			<EndDateTime>2006-05-14</EndDateTime>
			<Duration>PT4H</Duration>
		</TimeInterval>
		<TimeInterval type="Sickness" actionCode="Unchanged">
			<StartDateTime>2006-05-14</StartDateTime>
			<EndDateTime>2006-05-14</EndDateTime>
			<Duration>PT4H</Duration>
		</TimeInterval>
		<TimeInterval type="Sickness" actionCode="Void">
			<StartDateTime>2006-05-15</StartDateTime>
			<EndDateTime>2006-05-18</EndDateTime>
		</TimeInterval>
	</ReportedTime>
</TimeCard>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/TimeCard/TimeCard3.xml
<?xml version="1.0" encoding="UTF-8"?>
<TimeCard xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
TimeCard.xsd">
	<ReportedResource>
		<Person>
			<Id>
				<IdValue>d026194</IdValue>
			</Id>
		</Person>
	</ReportedResource>
	<ReportedTime>
		<PeriodStartDate>2001-05-01</PeriodStartDate>
		<PeriodEndDate>2001-05-18</PeriodEndDate>
		<TimeEvent type="Clock-in">
			<EventDateTime>2001-05-07T08:01:00Z</EventDateTime>
			<AdditionalData type="Order">1212</AdditionalData>
		</TimeEvent>
		<TimeEvent type="Clock-out">
			<EventDateTime>2001-05-07T12:03:00Z</EventDateTime>
		</TimeEvent>
		<TimeEvent type="Clock-in">
			<EventDateTime>2001-05-07T12:32:00Z</EventDateTime>
			<AdditionalData type="Order">1213</AdditionalData>
		</TimeEvent>
		<TimeEvent type="Clock-out">
			<EventDateTime>2001-05-07T17:05:00Z</EventDateTime>
		</TimeEvent>
		<TimeEvent type="Clock-in">
			<EventDateTime>2001-05-08T07:59:00Z</EventDateTime>
			<AdditionalData type="Order">1213</AdditionalData>
		</TimeEvent>
		<TimeEvent type="Clock-out">
			<EventDateTime>2001-05-08T10:04:00Z</EventDateTime>
		</TimeEvent>
	</ReportedTime>
</TimeCard>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/TimeCard/TimeCard2.xml
<?xml version="1.0" encoding="UTF-8"?>
<TimeCard xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
TimeCard.xsd">
	<ReportedResource>
		<Person>
			<Id>
				<IdValue>d026194</IdValue>
			</Id>
		</Person>
	</ReportedResource>
	<ReportedTime>
		<PeriodStartDate>2001-05-01</PeriodStartDate>
		<PeriodEndDate>2001-05-18</PeriodEndDate>
		<TimeInterval type="Regular" billable="true">
			<StartDateTime>2001-05-07T08:00:00</StartDateTime>
			<EndDateTime>2001-05-07T19:00:00</EndDateTime>
			<AdditionalData type="Task">Repair</AdditionalData>
			<AdditionalData type="Order">1212</AdditionalData>
			<Comment>Aaabbbccc</Comment>
		</TimeInterval>
		<Expense type="Meal" billable="true">
			<ExpenseDate>2001-05-07</ExpenseDate>
			<ExpenseAmount currency="USD">10</ExpenseAmount>
			<AdditionalData type="Order">1212</AdditionalData>
		</Expense>
		<TimeInterval type="Vacation">
			<StartDateTime>2001-05-08</StartDateTime>
			<EndDateTime>2001-05-11</EndDateTime>
		</TimeInterval>
		<TimeInterval type="Regular">
			<StartDateTime>2001-05-14T08:00:00</StartDateTime>
			<EndDateTime>2001-05-14T12:00:00</EndDateTime>
			<PieceWork>
				<Piece>
					<PieceValue>gadget</PieceValue>
				</Piece>
				<Quantity>40</Quantity>
			</PieceWork>
			<AdditionalData type="Task">Production</AdditionalData>
		</TimeInterval>
		<TimeInterval type="Sickness">
			<StartDateTime>2001-05-14T13:00:00</StartDateTime>
			<EndDateTime>2001-05-14T17:00:00</EndDateTime>
		</TimeInterval>
		<TimeInterval type="Sickness">
			<StartDateTime>2001-05-15T08:00:00</StartDateTime>
			<EndDateTime>2001-05-18T12:00:00</EndDateTime>
		</TimeInterval>
	</ReportedTime>
</TimeCard>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/TimeCard/TimeCard4.xml
<?xml version="1.0" encoding="UTF-8"?>
<TimeCard xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
TimeCard.xsd">
	<ReportedResource>
		<Person>
			<Id>
				<IdValue>d026194</IdValue>
			</Id>
		</Person>
	</ReportedResource>
	<ReportedTime>
		<PeriodStartDate>2001-05-01</PeriodStartDate>
		<PeriodEndDate>2001-05-18</PeriodEndDate>
		<TimeInterval type="Regular" billable="true">
			<StartDateTime>2001-05-07T08:00:00</StartDateTime>
			<EndDateTime>2001-05-07T17:00:00</EndDateTime>
			<Duration>PT8H</Duration>
			<AdditionalData type="Task">Repair</AdditionalData>
			<AdditionalData type="Order">1212</AdditionalData>
			<AdditionalData type="CostCenter">700</AdditionalData>
		</TimeInterval>
		<TimeInterval type="Overtime" billable="true">
			<StartDateTime>2001-05-07T07:00:00</StartDateTime>
			<EndDateTime>2001-05-07T19:00:00</EndDateTime>
			<Duration>PT2H</Duration>
			<AdditionalData type="Task">Repair</AdditionalData>
			<AdditionalData type="Order">1212</AdditionalData>
			<AdditionalData type="CostCenter">700</AdditionalData>
			<Comment>Aaabbbccc</Comment>
		</TimeInterval>
		<TimeInterval type="Dirty Work" billable="false">
			<StartDateTime>2001-05-07</StartDateTime>
			<EndDateTime>2001-05-07</EndDateTime>
			<RateOrAmount currency="USD" type="hourly">20</RateOrAmount>
			<AdditionalData type="Task">Repair</AdditionalData>
			<AdditionalData type="Order">1212</AdditionalData>
			<AdditionalData type="CostCenter">700</AdditionalData>
		</TimeInterval>
		<Expense type="Meal" billable="true">
			<ExpenseDate>2001-05-07</ExpenseDate>
			<ExpenseAmount currency="USD">10</ExpenseAmount>
			<AdditionalData type="Order">1212</AdditionalData>
			<AdditionalData type="CostCenter">700</AdditionalData>
		</Expense>
		<TimeInterval type="Vacation">
			<StartDateTime>2001-05-08</StartDateTime>
			<EndDateTime>2001-05-11</EndDateTime>
			<Duration>PT32H</Duration>
		</TimeInterval>
		<TimeInterval type="Regular" billable="true">
			<StartDateTime>2001-05-14T08:00:00</StartDateTime>
			<EndDateTime>2001-05-14T17:00:00</EndDateTime>
			<Duration>PT4H</Duration>
			<AdditionalData type="Task">Production</AdditionalData>
			<AdditionalData type="CostCenter">800</AdditionalData>
		</TimeInterval>
		<TimeInterval type="Sickness">
			<StartDateTime>2001-05-14T13:00:00</StartDateTime>
			<EndDateTime>2001-05-14T17:00:00</EndDateTime>
			<Duration>PT4H</Duration>
		</TimeInterval>
		<TimeInterval type="Sickness">
			<StartDateTime>2001-05-15T08:00:00</StartDateTime>
			<EndDateTime>2001-05-18T15:00:00</EndDateTime>
			<Duration>PT4H</Duration>
		</TimeInterval>
	</ReportedTime>
</TimeCard>
