=== elevate/sharpresume/HRXML200704/HR-XML-2_5/Stock/ExerciseConfirmation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.hr-xml.org/2007-04-15" elementFormDefault="qualified" version="2007-04-15">
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: ExerciseConfirmation.xsd
Status: Recommendation
Date this version: 2007-04-15
Author(s): Andreas Bold - SAP, Stock Work Group
Documentation: EmployeeStocksPlanInterface.html

Terms of license can be found in license.txt.

		</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="../CPO/EntityIdType.xsd"/>
	<xsd:include schemaLocation="../CPO/UserArea.xsd"/>
	<xsd:include schemaLocation="../CPO/ISOUtilities.xsd"/>
	<xsd:complexType name="ExerciseConfirmationType">
		<xsd:sequence>
			<xsd:element name="Id" type="EntityIdType"/>
			<xsd:element name="ParticipantId" type="EntityIdType"/>
			<xsd:element name="ExerciseDate" type="LocalDateType"/>
			<xsd:element name="ExerciseInfo">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="GrantId" type="EntityIdType"/>
						<xsd:element name="OptionsExercised" type="xsd:decimal"/>
						<xsd:element name="GrantPrice" minOccurs="0">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:decimal">
										<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="SharesTradedForTax" type="xsd:decimal"/>
						<xsd:element name="SharesSwapped" type="xsd:decimal"/>
						<xsd:element name="SharesSold" type="xsd:decimal"/>
						<xsd:element name="SARPercentCashRequested" type="xsd:decimal"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="FairMarketValueOnExerciseDate">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:decimal">
							<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ExerciseInstructions" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="SellToCoverOptions" type="xsd:boolean"/>
						<xsd:element name="SellToCoverTaxes" type="xsd:boolean"/>
						<xsd:element name="SellToCoverFees" type="xsd:boolean"/>
						<xsd:element name="UseSharesForTaxes" type="xsd:boolean"/>
						<xsd:element name="UseSharesFirst" type="xsd:boolean"/>
						<xsd:element name="TaxRelevantPrice">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:decimal">
										<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="TaxInfo" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="TaxDate" type="LocalDateType"/>
						<xsd:element name="TaxType" type="xsd:string"/>
						<xsd:element name="TaxationLocation">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="CountryCode" type="CountryCodeType" minOccurs="0"/>
									<xsd:element name="Region" type="xsd:string" minOccurs="0"/>
									<xsd:element name="Municipality" type="xsd:string" minOccurs="0"/>
									<xsd:element name="PostalCode" type="xsd:string" minOccurs="0"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="TaxAmount">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:decimal">
										<xsd:attribute name="currency" type="CurrencyCodeType" use="required"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element ref="UserArea" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="ExerciseConfirmation" type="ExerciseConfirmationType"/>
</xsd:schema>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/Stock/ExerciseConfirmation1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ExerciseConfirmation xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
ExerciseConfirmation.xsd">
	<Id>
		<IdValue>EC-1</IdValue>
	</Id>
	<ParticipantId>
		<IdValue>P-1</IdValue>
	</ParticipantId>
	<ExerciseDate>2002-07-14</ExerciseDate>
	<ExerciseInfo>
		<GrantId>
			<IdValue>G-1</IdValue>
		</GrantId>
		<OptionsExercised>200</OptionsExercised>
		<SharesTradedForTax>0</SharesTradedForTax>
		<SharesSwapped>0</SharesSwapped>
		<SharesSold>0</SharesSold>
		<SARPercentCashRequested>0</SARPercentCashRequested>
	</ExerciseInfo>
	<FairMarketValueOnExerciseDate currency="EUR">187</FairMarketValueOnExerciseDate>
	<ExerciseInstructions>
		<SellToCoverOptions>true</SellToCoverOptions>
		<SellToCoverTaxes>false</SellToCoverTaxes>
		<SellToCoverFees>false</SellToCoverFees>
		<UseSharesForTaxes>false</UseSharesForTaxes>
		<UseSharesFirst>false</UseSharesFirst>
		<TaxRelevantPrice currency="EUR">187</TaxRelevantPrice>
	</ExerciseInstructions>
	<TaxInfo>
		<TaxDate>2002-07-14</TaxDate>
		<TaxType>Einkommenssteuer</TaxType>
		<TaxationLocation>
			<CountryCode>DE</CountryCode>
		</TaxationLocation>
		<TaxAmount currency="EUR">6880</TaxAmount>
	</TaxInfo>
</ExerciseConfirmation>
