=== elevate/sharpresume/HRXML200704/HR-XML-2_5/Stock/StockPlan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ns.hr-xml.org/2007-04-15" elementFormDefault="qualified" version="2007-04-15">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../../W3C/xml.xsd"/>
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: StockPlan.xsd
Status: Recommendation
Date this version: 2007-04-15
Author(s): Andreas Bold - SAP, Stock Work Group
Documentation: EmployeeStocksPlanInterface.html

Terms of license can be found in license.txt.

Change History:
2005-01
As per Schema Design Guidelines, all default values have been removed.


		</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="../CPO/EntityIdType.xsd"/>
	<xsd:include schemaLocation="../CPO/UserArea.xsd"/>
	<xsd:include schemaLocation="../CPO/ISOUtilities.xsd"/>
	<xsd:include schemaLocation="../CPO/xStringPatternExtensionType.xsd"/>
	<xsd:simpleType name="StockPlanTypeEnumeration">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Stock Options"/>
			<xsd:enumeration value="Stock Purchase"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StockOptionPlanType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Qualified"/>
			<xsd:enumeration value="Non Qualified"/>
			<xsd:enumeration value="Stock Appreciation Rights"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StockPlanExtensionType">
		<xsd:union memberTypes="StockPlanTypeEnumeration xStringPatternExtensionType"/>
	</xsd:simpleType>
	<xsd:simpleType name="StockOptionPlanExtensionType">
		<xsd:union memberTypes="StockOptionPlanType xStringPatternExtensionType"/>
	</xsd:simpleType>
	<xsd:simpleType name="StockPurchasePlanType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Qualified"/>
			<xsd:enumeration value="Non Qualified"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StockPurchasePlanExtensionType">
		<xsd:union memberTypes="StockPurchasePlanType xStringPatternExtensionType"/>
	</xsd:simpleType>
	<xsd:complexType name="StockPlanType">
		<xsd:sequence>
			<xsd:element name="Id" type="EntityIdType"/>
			<xsd:element name="CompanyId" type="EntityIdType"/>
			<xsd:element name="PlanType" type="StockPlanExtensionType"/>
			<xsd:element name="Name" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute ref="xml:lang" use="required"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="Description" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute ref="xml:lang" use="required"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="Stock">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Id" type="EntityIdType"/>
						<xsd:element name="Symbol" type="xsd:string" minOccurs="0"/>
						<xsd:element name="Exchange" type="xsd:string" minOccurs="0"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="BlackOutInformation" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Period" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="validFrom" type="LocalDateType" use="required"/>
								<xsd:attribute name="validTo" type="LocalDateType" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:choice>
				<xsd:element name="StockOptionInfo">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="StockOptionType" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="StockOptionPlanExtensionType">
											<xsd:attribute name="country" type="CountryCodeType"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Ratio" type="xsd:integer"/>
							<xsd:element name="QualifiedGrantsAllowed" type="xsd:boolean"/>
							<xsd:element name="NonQualifiedGrantsAllowed" type="xsd:boolean"/>
							<xsd:element name="QualifiedGrantDefault">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="Qualified"/>
										<xsd:enumeration value="NonQualified"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="StockAppreciationRights">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="standalone"/>
										<xsd:enumeration value="tandem"/>
										<xsd:enumeration value="additive"/>
										<xsd:enumeration value="notApplicable"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="MaximumNumberOfShares" type="xsd:positiveInteger"/>
							<xsd:element name="MinimumNumberToExercise" type="xsd:positiveInteger"/>
							<xsd:element name="MaximumNumberToExercise" type="xsd:positiveInteger"/>
							<xsd:element name="BlocksToExercise" type="xsd:positiveInteger"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="StockPurchaseInfo">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="StockPurchaseType" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="StockPurchasePlanExtensionType">
											<xsd:attribute name="country" type="CountryCodeType"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="OfferingPeriod" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="validFrom" type="LocalDateType" use="required"/>
									<xsd:attribute name="validTo" type="LocalDateType" use="required"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="ContributionRulesDescription" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute ref="xml:lang" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="PurchaseRulesDescription" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute ref="xml:lang" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:element ref="UserArea" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="validFrom" type="LocalDateType" use="required"/>
		<xsd:attribute name="validTo" type="LocalDateType" use="required"/>
	</xsd:complexType>
	<xsd:element name="StockPlan" type="StockPlanType"/>
</xsd:schema>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/Stock/StockPlan2.xml
<?xml version="1.0" encoding="UTF-8"?>
<StockPlan xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
StockPlan.xsd" validFrom="2002-01-08" validTo="2006-11-08">
	<Id>
		<IdValue>SOP2002</IdValue>
	</Id>
	<CompanyId>
		<IdValue>%542201100</IdValue>
	</CompanyId>
	<PlanType>Stock Options</PlanType>
	<Name xml:lang="en">2002 Employee Stock Option Plan</Name>
	<Description xml:lang="en">2002 Employee Stock Option Plan - Compensation Plan 2002</Description>
	<Stock>
		<Id>
			<IdValue name="CUSIP">554100210</IdValue>
		</Id>
		<Symbol>AAA</Symbol>
		<Exchange>NYSE</Exchange>
	</Stock>
	<BlackOutInformation>
		<Period validFrom="2002-12-01" validTo="2003-01-02"/>                                                                              
	</BlackOutInformation>
	<StockOptionInfo>
		<StockOptionType country="US">Qualified</StockOptionType>               
		<Ratio>1</Ratio>
		<QualifiedGrantsAllowed>true</QualifiedGrantsAllowed>
		<NonQualifiedGrantsAllowed>true</NonQualifiedGrantsAllowed>
		<QualifiedGrantDefault>Qualified</QualifiedGrantDefault>
		<StockAppreciationRights>notApplicable</StockAppreciationRights>
		<MaximumNumberOfShares>2000000</MaximumNumberOfShares>
		<MinimumNumberToExercise>100</MinimumNumberToExercise>
		<MaximumNumberToExercise>10000</MaximumNumberToExercise>
		<BlocksToExercise>100</BlocksToExercise>
	</StockOptionInfo>
</StockPlan>

=== elevate/sharpresume/HRXML200704/HR-XML-2_5/Stock/StockPlan1.xml
<?xml version="1.0" encoding="UTF-8"?>
<StockPlan xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
StockPlan.xsd" validFrom="2001-01-01" validTo="2010-12-31">
	<Id>
		<IdValue>PL-1</IdValue>
	</Id>
	<CompanyId>
		<IdValue>C-1</IdValue>
	</CompanyId>
	<PlanType>Stock Options</PlanType>
	<Name xml:lang="en">Stock Option Plan 2001</Name>
	<Description xml:lang="en">Stock Option Plan 2001 for all employees</Description>
	<Stock>
		<Id>
			<IdValue name="ISIN">US0007164600</IdValue>
		</Id>
	</Stock>
	<BlackOutInformation>
		<Period validFrom="2001-03-15" validTo="2001-03-31"/>               
		<Period validFrom="2001-09-15" validTo="2001-09-30"/>
		<Period validFrom="2002-03-15" validTo="2002-03-31"/>                
		<Period validFrom="2002-09-15" validTo="2002-09-30"/>                
		<Period validFrom="2003-03-15" validTo="2003-03-31"/>                
		<Period validFrom="2003-09-15" validTo="2003-09-30"/>
		<Period validFrom="2004-03-15" validTo="2004-03-31"/>               
		<Period validFrom="2004-09-15" validTo="2004-09-30"/>
	</BlackOutInformation>
	<StockOptionInfo>               
		<Ratio>2</Ratio>
		<QualifiedGrantsAllowed>true</QualifiedGrantsAllowed>
		<NonQualifiedGrantsAllowed>true</NonQualifiedGrantsAllowed>
		<QualifiedGrantDefault>Qualified</QualifiedGrantDefault>
		<StockAppreciationRights>notApplicable</StockAppreciationRights>
		<MaximumNumberOfShares>2000000</MaximumNumberOfShares>
		<MinimumNumberToExercise>100</MinimumNumberToExercise>
		<MaximumNumberToExercise>1000</MaximumNumberToExercise>
		<BlocksToExercise>50</BlocksToExercise>
	</StockOptionInfo>
</StockPlan>
